apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: hack-istio-player-backend
  name: player-backend
  labels:
    app: player-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: player-backend
  template:
    metadata:
      labels:
        app: player-backend
    spec:
      serviceAccountName: player-backend-sa
      containers:
      - name: player-backend
        image: elessar1ch/playerbackend:latest
        ports:
        - containerPort: 3000
        env:
        - name: server_port
          value: 3000
        - name: instrument_port
          value: 8080
