apiVersion: v1
kind: Service
metadata:
  namespace: hack-istio-player-backend
  name: player-backend
spec:
  selector:
    app: player-backend
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 3000
